pipeline {
    agent { 
        node {
            label 'docker-agent-python'
            }
      }
    stages {
        stage('Build') {
            steps {
                echo "Starting to open file ..."
                sh '''
                echo "Building the requirements..."
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing python file ..."
                sh '''
                cd jenkins-pipeline
                ls -ltra
                python3 helloworld.py
                cd app
                python3 hello.py
                ls -ltra
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Print the code ....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}
